### ISSUE TITLE
Unable to launch UI (Request for ARM architecture support)

### ISSUE THREAD

**Issue by pearlmary** [neuronic-ai/autogpt-ui#2]
Hi Shawn,

I'm unable to load (https://localhost:8160/). Hmmm… can't reach this page. localhost refused to connect.

I've followed all the instructions correctly. Tried Connect with your browser on port 8160. And also, the IP of the machine its installed on.

Any Workaround to launch it.

**Comment by pearlmary** [comment]
Shawn, Here is the screenshot of docker ps -a
![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/c4ef3ea0-b6a3-41c9-a022-9c6441c96d7f)

**Comment by EncryptShawn** [comment]
So far when we see this its almost always that we are not communicating with MySQL properly. You can check the docker logs by typing "docker logs autogpt-ui-worker-1" and "docker logs autogpt-ui-api-1" or in  place of the names you can use the cointainer ID and almost certainly the error messages will be about not able to connect to mysql. 

Make sure you are trying to connect to "mysql" instead of "localhost" and be sure to use root as the login and the same password as you set in your env-mysql.env when configuring your mysql connection string.

So in the env-mysql.env it should look something like this but with your own password.

MYSQL_ROOT_PASSWORD=Password123
MYSQL_DATABASE=auto_gpt_ui

and in your env-backend.env it should look like this for your connection string but using the password you set in the env-mysql.env file and also the database should be the same name as you set in your mysql file as well..

DATABASE_URL=mysql://root:Password123@mysql:3306/auto_gpt_ui

If you see some other error than mysql connection issues in your logs, please post any logs that you can from these two containers.


Dont forget to sudo make all again after you update any of the env files.

**Comment by camAtGitHub** [comment]
I also had to set `NO_AUTH=True` (not to '1' as stated)  in `env-backend.env` otherwise I got this traceback from api container:  
```
✔ Generated Prisma Client Python (v0.8.2) to ./usr/local/lib/python3.11/site-packages/prisma in 229ms

Traceback (most recent call last):
  File "/usr/local/bin/arq", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arq/cli.py", line 40, in cli
    worker_settings_ = cast('WorkerSettingsType', import_string(worker_settings))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arq/utils.py", line 146, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/app/worker/main.py", line 8, in <module>
    from app.core import settings, init_logging
  File "/src/app/core/__init__.py", line 1, in <module>
    from .config import settings
  File "/src/app/core/config.py", line 78, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
NO_AUTH
  value could not be parsed to a boolean (type=type_error.bool)
```
Could also do with a example 'AI Settings file' being added to the repo.
This is mine:
```
ai_name: hello-bot
ai_role: 'You are a test bot. You perform very simple tasks as requested, nothing more.'
ai_goals:
  - If exists "/hello.txt" then delete it.
  - >-
    Create new file ./hello.txt with contents of "Hello World" + {RANDOM 10 CHAR
    STRING}
  - Confirm all self.ai_goals were completed in order.
```

But im stuck on this error:
```
  File "/src/app/auto_gpt/cli.py", line 123, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/app/auto_gpt/cli.py", line 99, in main
    from app.auto_gpt.main import run_auto_gpt
  File "/src/app/auto_gpt/main.py", line 26, in <module>
    from app.auto_gpt.agent import AgentStandalone
  File "/src/app/auto_gpt/agent.py", line 6, in <module>
    from autogpt.json_utils.json_fix_llm import fix_json_using_multiple_techniques
ModuleNotFoundError: No module named 'autogpt.json_utils.json_fix_llm'
```

Seems **core** files are missing?

**Comment by pearlmary** [comment]
> If you see some other error than mysql connection issues in your logs, please post any logs that you can from these two containers.

Hi Shawn,
After updating env-mysql.env, and the env-backend.env and sudo make all.
Unable to find where am I going wrong. 
Can you please help me out?

The results of docker logs autogpt-ui-worker-1
 ![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/6273969b-3c15-49b6-9fdd-771e4e4e4df4)


And the results of docker logs autogpt-ui-api-1
 ![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/12d721de-975d-4d05-97b6-52b296d71166)


And the results of docker logs autogpt-ui-frontend-1
 ![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/9402d61c-714b-4b1d-8944-bca659b3190b)


And the results of docker logs autogpt-ui-mysql-1
 
![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/f46bdb87-853a-42eb-8dc7-ecce6e1f8cee)


And the results of docker logs autogpt-ui-redis-1
 
![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/880b5041-a26f-4d29-ad69-a07debf0b4ae)


And the results of docker logs autogpt-ui-proxy-1
 
![image](https://github.com/neuronic-ai/autogpt-ui/assets/29123795/8ca00c92-9ace-435e-9d5e-21a14409a311)

**Comment by EncryptShawn** [comment]
Are you by chance running this on an ARM install? I see this error tends to happen when trying to run prisma on ARM but we have not made this code to run on Pi or similar devices, it needs a full on regular processor, AMD or Intel, but not ARM.

https://github.com/prisma/prisma/issues/9503

To determine if a system is ARM-based, you can use the "uname -m" command, which will display the machine hardware name. If it returns "aarch64" or "arm64," it indicates an ARM system. Other possible values for different architectures include "x86_64" for 64-bit x86 systems and "i686" for 32-bit x86 systems.

I noticed I almost chose arm version on Google because I think its fairly new and wasnt an option before and I think it was one of the first options. Between experiencing that on google and based on these specific errors, this is what I most suspect right now.  It would require you to rebuild but with just regular ubuntu and not ARM version. 

If you could please verify that it would be appreciated. 

Also we should be releasing the next release sometime in the next couple of weeks, so keep an eye out for that, a lot of very much needed updates.(Still no arm support though)

**Comment by merry75** [comment]
i have a mac with apple chip arm64 then 

managed to load the ui but then stuck at getting 502 http error on api somehow

**Comment by merry75** [comment]
same here using map with apple chip, so arm64 and stuck let us know when we can retry ;)

**Comment by EncryptShawn** [comment]
We are soon releasing 1.1 and we are working on 1.2 but unfortunately neither are supporting arm architecture. We may be able to look at it after that but also perhaps someone else with more development resources would consider forking and make an arm version. The 1.1 release would be a better starting point, quite a bit of needed updates and ui improvements missing from 1.0
