### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by lvlconceptss** [neuronic-ai/autogpt-ui#7]
Traceback (most recent call last):
  File "/usr/local/bin/prisma", line 5, in <module>
    from prisma.cli import main
  File "/usr/local/lib/python3.11/site-packages/prisma/__init__.py", line 11, in <module>
    from ._config import config as config
  File "/usr/local/lib/python3.11/site-packages/prisma/_config.py", line 7, in <module>
    from pydantic import BaseSettings, Extra, Field
  File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.
For further information visit https://errors.pydantic.dev/2.3/u/import-error

**Comment by harshitdeepsolv** [comment]
hey did you solve this error ?
